Create SPECIFICATION-DOCUMENT-REQUIREMENTS
eea-oasis/managed-open-project pull request #55
Opened 2022-02-22 18:35 UTC by tasdienes

New document for review

2022-02-22 18:38 UTC, burnburn approved these changes

2022-02-22 18:54 UTC, chaals requested changes
name it ...md so it gets presented nicely by Github.

Otherwise, LGTM

2022-02-22 19:50 UTC, tasdienes commented
Good call, thanks!

2022-02-22 20:58 UTC, chaals approved these changes

2022-02-23 22:29 UTC, tkuhrt approved these changes

2022-02-24 20:12 UTC, burnburn approved these changes

2022-02-24 20:16 UTC, burnburn commented
Approved in PGB meeting 24 Feb 2022.

2022-02-24 20:16 UTC, merged